
modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://my.issue.tracker/"
displayURL="http://lclpnet.work/" #optional
authors="LCLP" #optional

[[mods]]
    modId="lclpupdater"
    version="${version}"
    displayName="LCLPUpdateChecker"
    updateJSONURL="http://myurl.me/" #optional
    logoFile="logo.png" #optional
    credits="LCLPNetwork!" #optional
    description='''
    A small modification to check, if the installed installation of an LCLP Minecraft Environment is outdated.
    This mod also automatically starts the LCLPLauncher to update.
    '''
    
    [[dependencies.core]] #optional
        modId="forge" #mandatory
        mandatory=true #mandatory
        versionRange="[31,)" #mandatory
        ordering="NONE"
        side="BOTH"
    [[dependencies.core]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.15.2]"
        ordering="NONE"
        side="BOTH"

