
modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/LCLPYT/LCLPUpdateChecker/issues"
displayURL="https://github.com/LCLPYT/LCLPUpdateChecker"
authors="LCLP"

[[mods]]
    modId="lclpupdater"
    version="${version}"
    displayName="LCLPUpdateChecker"
    updateJSONURL="https://raw.githubusercontent.com/LCLPYT/LCLPUpdateChecker/master/LCLPUpdateChecker/update.json"
    logoFile="logo.png"
    credits="LCLPNetwork!"
    description='''
    A small modification to check, if the installed installation of an LCLP Minecraft Environment is outdated.
    This mod also automatically starts the LCLPLauncher to update.
    '''
    
    [[dependencies.lclpupdater]]
        modId="forge"
        mandatory=true
        versionRange="[31,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.lclpupdater]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.15.2]"
        ordering="NONE"
        side="BOTH"

